/*
-- Query: SELECT * FROM narwhal.cca
LIMIT 0, 1000

-- Date: 2018-07-18 00:04
*/
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (1,'Basketball','Sports','NYP’s Basketball team brings together all enthusiasts of the game from the student population in NYP, whether the students prefer to play competitively or for leisure.','Stadium','2018-07-04','2018-07-01 16:51:00','basketball.jpg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (2,'Football','Sports','The NYP Soccer Team is a recreational and competitive sports club open to all NYP students. Apart from training hard to become better soccer players, we join soccer competitions, watch soccer matches together and talk about soccer. We also organise Futsal tournaments and an overseas camp that members can look forward to. In 2012, the inaugural Futbol Sala was held in NYP. It was a 5-sided competition and 20 teams participated in the competition.','Field','2018-06-06','2018-07-01 15:23:34','football.jpeg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (3,'Taekwondo','Sports','NYP’s Taekwondo Club was formed to bring together students who are passionate about this form of martial arts.','Indoor Stadium','2018-05-05','2018-07-01 15:23:34','taekwondo.jpg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (4,'Netball','Sports','NYP Netball Club is a competitive team CCA and is open to all females who have a passion for Netball. An individual must be willing to learn and grow together as a team. The netballers are very well-bonded and assist in organising sports events in NYP. The team also participates in external competitions organized by Netball Singapore in preparation for the POL-ITE and IVP Games.','Indoor Stadium','2018-05-05','2018-07-01 15:23:34','netball.jpg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (5,'Basketball','Sports','NYP’s Basketball team brings together all enthusiasts of the game from the student population in NYP, whether the students prefer to play competitively or for leisure.','Stadium','2018-07-04','2018-07-01 15:23:34','basketball.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (6,'Basketball','Sports','NYP’s Basketball team brings together all enthusiasts of the game from the student population in NYP, whether the students prefer to play competitively or for leisure.','Stadium','2018-07-04','2018-07-01 15:23:34','basketball.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (7,'Basketball','Sports','NYP’s Basketball team brings together all enthusiasts of the game from the student population in NYP, whether the students prefer to play competitively or for leisure.','Stadium','2018-07-04','2018-07-01 15:23:34','basketball.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (8,'Basketball','Sports','NYP’s Basketball team brings together all enthusiasts of the game from the student population in NYP, whether the students prefer to play competitively or for leisure.','Stadium','2018-07-04','2018-07-01 15:23:34','basketball.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (9,'Netball','Sports','NYP Netball Club is a competitive team CCA and is open to all females who have a passion for Netball. An individual must be willing to learn and grow together as a team. The netballers are very well-bonded and assist in organising sports events in NYP. The team also participates in external competitions organized by Netball Singapore in preparation for the POL-ITE and IVP Games.','Indoor Stadium','2018-05-05','2018-07-01 15:23:34','netball.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (10,'Taekwondo','Sports','NYP’s Taekwondo Club was formed to bring together students who are passionate about this form of martial arts.','Indoor Stadium','2018-05-05','2018-07-01 15:23:34','taekwondo.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (11,'asdesd111123123','asdasd','asd12123','asd','0000-00-00','2018-07-01 14:51:33','asd','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (14,'123123','123','123','123','0000-00-00','2018-07-01 14:51:33','123','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`trgTime`,`image`,`featured`) VALUES (21,'dt','wer','rwe','gfh','0000-00-00','2018-07-01 14:51:33','as','0');
