/*
-- Query: SELECT * FROM narwhal.cca
LIMIT 0, 1000

-- Date: 2018-08-01 21:37
*/
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (2,'Football','Sports','The NYP Soccer Team is a recreational and competitive sports club open to all NYP students. Apart from training hard to become better soccer players, we join soccer competitions, watch soccer matches together and talk about soccer. We also organise Futsal tournaments and an overseas camp that members can look forward to. In 2012, the inaugural Futbol Sala was held in NYP. It was a 5-sided competition and 20 teams participated in the competition.','Field','2018-06-06','15:00:00','2018-07-29 14:19:46','football.jpeg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (3,'Taekwondo','Sports','NYP’s Taekwondo Club was formed to bring together students who are passionate about this form of martial arts.','Indoor Stadium','2018-05-05','15:00:00','2018-07-29 14:19:46','taekwondo.jpg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (4,'Netball','Sports','NYP Netball Club is a competitive team CCA and is open to all females who have a passion for Netball. An individual must be willing to learn and grow together as a team. The netballers are very well-bonded and assist in organising sports events in NYP. The team also participates in external competitions organized by Netball Singapore in preparation for the POL-ITE and IVP Games.','Indoor Stadium','2018-05-05','15:00:00','2018-07-29 14:19:46','netball.jpg','1');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (28,'Swimming','Sports','NYP’s Swim Team is made up of a group of disciplined and tightly knit swimmers who hone their skills either for recreational or competitive purposes through regular training sessions. \r\n\r\nWithin the club, our members aim to make all feel comfortable and have a meaningful experience while forging friendships with like-minded individuals. Our club encourages and values relationships, thus regular bonding sessions such as social gatherings are organised. Most importantly, the club aims to swim, tra','Swimming Pool Area','2018-08-12',NULL,'0000-00-00 00:00:00','swimming-bg.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (8,'Basketball','Sports','NYP’s Basketball team brings together all enthusiasts of the game from the student population in NYP, whether the students prefer to play competitively or for leisure.','Stadium','2018-07-04','15:00:00','2018-07-29 14:19:46','basketball.jpg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (26,'Chinese Orchestra','Arts and Culture','The Nanyang Polytechnic Chinese Orchestra (NYPCO) was formed in September 1996 with a pioneer batch of 45 members. Today, it boasts of 120 members from our 7 different schools comprising of full-time students as well as alumni members who return regularly to practise and perform. Beyond traditional Chinese music, the Orchestra has experimented with a diverse selection of western pieces, contemporary music, Asian pop songs as well as other genres. Recently, the Orchestra has also formed a Percuss','Music Room','2018-01-12','20:00:00','2018-08-01 21:29:07','Chinese_Orchestra.jpeg','0');
INSERT INTO `cca` (`ccaID`,`name`,`category`,`information`,`venue`,`trgDate`,`startTime`,`trgTime`,`image`,`featured`) VALUES (27,'SIT Club','Academic Clubs','School of Information Technology (SIT) Club aims to foster bonding and build friendship among students through a range of exciting activities with a family-like approach. Students are offered many opportunities to develop life skills, leadership qualities and 21st century core competencies through enrichment programmes, student club activities and competitions. There are currently 25 students in the committee across 6 sub-committees; Ambassador, Social and Sports, Community and Student Support, ','SIT','2018-08-10',NULL,'0000-00-00 00:00:00','sit-club.png','0');
